// <auto-generated />
using System;
using FMMI_Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FMMI_Domain.Migrations
{
    [DbContext(typeof(FMMIContext))]
    [Migration("20251017063956_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FMMI_Domain.Entities.Alarm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Topics")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Alarms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "e4baec7a-02ac-4875-9c9f-97d7d4d0986b",
                            Description = "This is the default alarm.",
                            Name = "Default Alarm",
                            Topics = "test",
                            Value = 0.0
                        });
                });

            modelBuilder.Entity("FMMI_Domain.Entities.Data", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("DataTypeID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Dates")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeviceID")
                        .HasColumnType("integer");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("ID");

                    b.HasIndex("DataTypeID");

                    b.HasIndex("DeviceID");

                    b.ToTable("TelemetriData");
                });

            modelBuilder.Entity("FMMI_Domain.Entities.DataType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "50933a24-f7cc-41dd-af11-be52b7bcc627",
                            TypeName = "Temperature",
                            Unit = "°C"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "0d443d2c-144f-488d-b003-e84ca2b1a848",
                            TypeName = "Humidity",
                            Unit = "%"
                        });
                });

            modelBuilder.Entity("FMMI_Domain.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlarmID")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DeviceTypeID")
                        .HasColumnType("integer");

                    b.Property<int>("LocationID")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlarmID");

                    b.HasIndex("DeviceTypeID");

                    b.HasIndex("LocationID");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlarmID = 1,
                            ConcurrencyStamp = "283dbf03-6f12-47e6-acf4-970f87dda610",
                            DeviceTypeID = 1,
                            LocationID = 1,
                            Name = "TempSensor1"
                        },
                        new
                        {
                            Id = 2,
                            AlarmID = 1,
                            ConcurrencyStamp = "1b8ec008-2c2d-4077-9c1d-b3c224dc031f",
                            DeviceTypeID = 1,
                            LocationID = 1,
                            Name = "HumiditySensor1"
                        },
                        new
                        {
                            Id = 3,
                            AlarmID = 1,
                            ConcurrencyStamp = "bb1ad2b2-b9a1-403c-8dda-2f807b34d357",
                            DeviceTypeID = 1,
                            LocationID = 2,
                            Name = "TempSensor2"
                        },
                        new
                        {
                            Id = 4,
                            AlarmID = 1,
                            ConcurrencyStamp = "06360baf-4182-41b3-8194-28b23b08b727",
                            DeviceTypeID = 1,
                            LocationID = 2,
                            Name = "HumiditySensor2"
                        });
                });

            modelBuilder.Entity("FMMI_Domain.Entities.DeviceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DeviceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "4f0490fb-2ec2-47df-86cd-b69e9a26effd",
                            Name = "Sensor"
                        });
                });

            modelBuilder.Entity("FMMI_Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "5467f196-eee2-4316-9429-6e514072cb49",
                            Description = "Placering af første maskine",
                            Name = "Warehouse A"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "dbac44d6-336e-4557-9d5c-7adbd1425173",
                            Description = "Placering af anden maskine",
                            Name = "Warehouse B"
                        });
                });

            modelBuilder.Entity("FMMI_Domain.Entities.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LocationID")
                        .HasColumnType("integer");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LocationID");

                    b.ToTable("Machine");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "5e9f19fd-2853-4679-9bce-d40d1de584c4",
                            LocationID = 1,
                            MachineName = "Machine A"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "828280ea-aed4-4d16-844c-0eb9fcee6457",
                            LocationID = 2,
                            MachineName = "Machine B"
                        });
                });

            modelBuilder.Entity("FMMI_Domain.Entities.Data", b =>
                {
                    b.HasOne("FMMI_Domain.Entities.DataType", "DataType")
                        .WithMany()
                        .HasForeignKey("DataTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMMI_Domain.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataType");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("FMMI_Domain.Entities.Device", b =>
                {
                    b.HasOne("FMMI_Domain.Entities.Alarm", "Alarm")
                        .WithMany()
                        .HasForeignKey("AlarmID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMMI_Domain.Entities.DeviceType", "DeviceType")
                        .WithMany()
                        .HasForeignKey("DeviceTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMMI_Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alarm");

                    b.Navigation("DeviceType");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("FMMI_Domain.Entities.Machine", b =>
                {
                    b.HasOne("FMMI_Domain.Entities.Location", "Locations")
                        .WithMany()
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
